### ISSUE TITLE
Cannot be installed

### ISSUE THREAD

**Issue by BRoeske** [HGlab01/ioBroker.followthesun#722]
Impossible to install due to...

$ iobroker add followthesun --host iobroker

NPM version: 9.6.7Installing iobroker.followthesun@0.5.1... (System call)

npm ERR! code EBADENGINEnpm ERR! engine Unsupported enginenpm ERR! engine Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@8.6.0npm ERR! notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@8.6.0npm ERR! notsup Required: {"node":"^18.18.0 || ^20.9.0 || >=21.1.0"}npm ERR! notsup Actual: {"npm":"9.6.7","node":"v18.17.1"}npm ERR! A complete log of this run can be found in: /opt/iobroker/.npm/_logs/2024-09-20T12_38_03_117Z-debug-0.log

host.iobroker Cannot install iobroker.followthesun@0.5.1: 1

ERROR: Process exited with code 25

No idea about the problem, because I cannot understand the error message.

**Comment by HGlab01** [comment]
I would highly appreciate if you would use the template for creating a bug ticket

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '....'
4. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Add any other context about the problem here.

**Comment by HGlab01** [comment]
ERR! notsup **Required**: {"**node":"^18.18.0** || ^20.9.0 || >=21.1.0"}
ERR! notsup **Actual**: {"npm":"9.6.7",**"node":"v18.17.1"**}

Please upgrade node18 to 18.18.0 or higher or node20 to 20.9.0 or higher
